<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 4 Exponential Smoothing (ETS) | Time Series Analysis</title>
  <meta name="description" content="Time series analysis using R." />
  <meta name="generator" content="bookdown 0.35 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 4 Exponential Smoothing (ETS) | Time Series Analysis" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="Time series analysis using R." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 4 Exponential Smoothing (ETS) | Time Series Analysis" />
  
  <meta name="twitter:description" content="Time series analysis using R." />
  

<meta name="author" content="Michael Foley" />


<meta name="date" content="2023-08-31" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="regression.html"/>
<link rel="next" href="arima.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<link href="libs/tabwid-1.1.3/tabwid.css" rel="stylesheet" />
<script src="libs/tabwid-1.1.3/tabwid.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>
<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Time Series Analysis in R</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a></li>
<li class="chapter" data-level="1" data-path="toolbox.html"><a href="toolbox.html"><i class="fa fa-check"></i><b>1</b> Toolbox</a>
<ul>
<li class="chapter" data-level="1.1" data-path="toolbox.html"><a href="toolbox.html#common-frameworks"><i class="fa fa-check"></i><b>1.1</b> Common Frameworks</a></li>
<li class="chapter" data-level="1.2" data-path="toolbox.html"><a href="toolbox.html#fitting-models"><i class="fa fa-check"></i><b>1.2</b> Fitting Models</a></li>
<li class="chapter" data-level="1.3" data-path="toolbox.html"><a href="toolbox.html#evaluating-fit"><i class="fa fa-check"></i><b>1.3</b> Evaluating Fit</a></li>
<li class="chapter" data-level="1.4" data-path="toolbox.html"><a href="toolbox.html#evaluating-accuracy"><i class="fa fa-check"></i><b>1.4</b> Evaluating Accuracy</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="exporation.html"><a href="exporation.html"><i class="fa fa-check"></i><b>2</b> Exploratory Analysis</a>
<ul>
<li class="chapter" data-level="2.1" data-path="exporation.html"><a href="exporation.html#graphical-analysis"><i class="fa fa-check"></i><b>2.1</b> Graphical Analysis</a></li>
<li class="chapter" data-level="2.2" data-path="exporation.html"><a href="exporation.html#transformations"><i class="fa fa-check"></i><b>2.2</b> Transformations</a></li>
<li class="chapter" data-level="2.3" data-path="exporation.html"><a href="exporation.html#decomposition"><i class="fa fa-check"></i><b>2.3</b> Decomposition</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="exporation.html"><a href="exporation.html#classical-decomposition"><i class="fa fa-check"></i><b>2.3.1</b> Classical Decomposition</a></li>
<li class="chapter" data-level="2.3.2" data-path="exporation.html"><a href="exporation.html#x-11-and-seats"><i class="fa fa-check"></i><b>2.3.2</b> X-11 and SEATS</a></li>
<li class="chapter" data-level="2.3.3" data-path="exporation.html"><a href="exporation.html#stl"><i class="fa fa-check"></i><b>2.3.3</b> STL</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="regression.html"><a href="regression.html"><i class="fa fa-check"></i><b>3</b> Time Series Regression</a>
<ul>
<li class="chapter" data-level="3.1" data-path="regression.html"><a href="regression.html#exploratory-analysis"><i class="fa fa-check"></i><b>3.1</b> Exploratory Analysis</a></li>
<li class="chapter" data-level="3.2" data-path="regression.html"><a href="regression.html#fit-model"><i class="fa fa-check"></i><b>3.2</b> Fit Model</a>
<ul>
<li class="chapter" data-level="" data-path="regression.html"><a href="regression.html#special-predictors"><i class="fa fa-check"></i>Special Predictors</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="regression.html"><a href="regression.html#model-evaluation"><i class="fa fa-check"></i><b>3.3</b> Model Evaluation</a>
<ul>
<li class="chapter" data-level="" data-path="regression.html"><a href="regression.html#outliers-leverage-points-and-influential-points"><i class="fa fa-check"></i>Outliers, Leverage Points, and Influential Points</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="regression.html"><a href="regression.html#variable-selection"><i class="fa fa-check"></i><b>3.4</b> Variable Selection</a></li>
<li class="chapter" data-level="3.5" data-path="regression.html"><a href="regression.html#predicting-values"><i class="fa fa-check"></i><b>3.5</b> Predicting Values</a></li>
<li class="chapter" data-level="3.6" data-path="regression.html"><a href="regression.html#nonlinear-regression"><i class="fa fa-check"></i><b>3.6</b> Nonlinear Regression</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="exponential.html"><a href="exponential.html"><i class="fa fa-check"></i><b>4</b> Exponential Smoothing (ETS)</a>
<ul>
<li class="chapter" data-level="4.1" data-path="exponential.html"><a href="exponential.html#simple-exponential-smoothing-ses"><i class="fa fa-check"></i><b>4.1</b> Simple Exponential Smoothing (SES)</a></li>
<li class="chapter" data-level="4.2" data-path="exponential.html"><a href="exponential.html#holt-linear"><i class="fa fa-check"></i><b>4.2</b> Holt Linear</a></li>
<li class="chapter" data-level="4.3" data-path="exponential.html"><a href="exponential.html#additive-damped-trend"><i class="fa fa-check"></i><b>4.3</b> Additive Damped Trend</a></li>
<li class="chapter" data-level="4.4" data-path="exponential.html"><a href="exponential.html#holt-winters"><i class="fa fa-check"></i><b>4.4</b> Holt-Winters</a></li>
<li class="chapter" data-level="4.5" data-path="exponential.html"><a href="exponential.html#model-selection-with-cv"><i class="fa fa-check"></i><b>4.5</b> Model Selection with CV</a></li>
<li class="chapter" data-level="4.6" data-path="exponential.html"><a href="exponential.html#model-selection-via-maximum-likelihood"><i class="fa fa-check"></i><b>4.6</b> Model Selection via Maximum Likelihood</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="arima.html"><a href="arima.html"><i class="fa fa-check"></i><b>5</b> ARIMA</a>
<ul>
<li class="chapter" data-level="5.1" data-path="arima.html"><a href="arima.html#tranformations-and-differencing"><i class="fa fa-check"></i><b>5.1</b> Tranformations and Differencing</a></li>
<li class="chapter" data-level="5.2" data-path="arima.html"><a href="arima.html#autoregressive-models"><i class="fa fa-check"></i><b>5.2</b> Autoregressive Models</a></li>
<li class="chapter" data-level="5.3" data-path="arima.html"><a href="arima.html#moving-average-models"><i class="fa fa-check"></i><b>5.3</b> Moving Average Models</a></li>
<li class="chapter" data-level="5.4" data-path="arima.html"><a href="arima.html#non-seasonal-arima"><i class="fa fa-check"></i><b>5.4</b> Non-Seasonal ARIMA</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="dynamic.html"><a href="dynamic.html"><i class="fa fa-check"></i><b>6</b> Dynamic Harmonic Regression</a>
<ul>
<li class="chapter" data-level="6.1" data-path="dynamic.html"><a href="dynamic.html#tbats-model"><i class="fa fa-check"></i><b>6.1</b> TBATS Model</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Time Series Analysis</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="exponential" class="section level1 hasAnchor" number="4">
<h1><span class="header-section-number">Chapter 4</span> Exponential Smoothing (ETS)<a href="exponential.html#exponential" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>Exponential smoothing methods are weighted averages of past observations, with the weights decaying exponentially as the observations get more remote. Exponential smoothing is a family of methods that vary by their <em>trend</em> and <em>seasonal</em> components.</p>
<div class="tabwid tabwid_left"><style>.cl-a5733c62{}.cl-a56b4cfa{font-family:'Arial';font-size:10pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-a56b4d04{font-family:'Arial';font-size:10pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-a56e93f6{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-a56e9400{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-a56e940a{margin:0;text-align:right;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-a56e9414{margin:0;text-align:justify;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-a56e9415{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:5pt;padding-top:5pt;padding-left:5pt;padding-right:5pt;line-height: 1;background-color:transparent;}.cl-a56eac60{width:1.644in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(204, 204, 204, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a56eac6a{width:2.177in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a56eac6b{width:1.582in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a56eac6c{width:1.883in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a56eac74{width:1.644in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(204, 204, 204, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a56eac75{width:2.177in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a56eac76{width:1.582in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a56eac77{width:1.883in;background-color:transparent;vertical-align: middle;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 1.5pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a56eac7e{width:1.644in;background-color:transparent;vertical-align: top;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(204, 204, 204, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a56eac7f{width:2.177in;background-color:transparent;vertical-align: top;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a56eac80{width:1.582in;background-color:transparent;vertical-align: top;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a56eac88{width:1.883in;background-color:transparent;vertical-align: top;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a56eac92{width:1.644in;background-color:transparent;vertical-align: top;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(204, 204, 204, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a56eac93{width:2.177in;background-color:transparent;vertical-align: top;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a56eac94{width:1.582in;background-color:transparent;vertical-align: top;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a56eac9c{width:1.883in;background-color:transparent;vertical-align: top;border-bottom: 0.75pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a56eac9d{width:1.644in;background-color:transparent;vertical-align: top;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 1pt solid rgba(204, 204, 204, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a56eac9e{width:2.177in;background-color:transparent;vertical-align: top;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a56eac9f{width:1.582in;background-color:transparent;vertical-align: top;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-a56eaca0{width:1.883in;background-color:transparent;vertical-align: top;border-bottom: 1.5pt solid rgba(102, 102, 102, 1.00);border-top: 0.75pt solid rgba(102, 102, 102, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing='true' class='cl-a5733c62'>

<caption style="display:table-caption;margin:0pt;text-align:left;border-bottom: 0.00pt solid transparent;border-top: 0.00pt solid transparent;border-left: 0.00pt solid transparent;border-right: 0.00pt solid transparent;padding-top:3pt;padding-bottom:3pt;padding-left:3pt;padding-right:3pt;line-height: 1;background-color:transparent;">
<span id="tab:unnamed-chunk-3">Table 4.1: </span><span>Exponential smoothing taxonomy.</span>
</caption>

<thead><tr style="overflow-wrap:break-word;"><th class="cl-a56eac60"><p class="cl-a56e93f6"><span class="cl-a56b4cfa"></span></p></th><th  colspan="3"class="cl-a56eac6a"><p class="cl-a56e9400"><span class="cl-a56b4cfa">Seasonal Component</span></p></th></tr><tr style="overflow-wrap:break-word;"><th class="cl-a56eac74"><p class="cl-a56e93f6"><span class="cl-a56b4cfa">Trend Component</span></p></th><th class="cl-a56eac75"><p class="cl-a56e93f6"><span class="cl-a56b4cfa">None (N)</span></p></th><th class="cl-a56eac76"><p class="cl-a56e93f6"><span class="cl-a56b4cfa">Additive (A)</span></p></th><th class="cl-a56eac77"><p class="cl-a56e93f6"><span class="cl-a56b4cfa">Multiplicative (M)</span></p></th></tr></thead><tbody><tr style="overflow-wrap:break-word;"><td class="cl-a56eac7e"><p class="cl-a56e9415"><span class="cl-a56b4d04">None (N)</span></p></td><td class="cl-a56eac7f"><p class="cl-a56e9415"><span class="cl-a56b4d04">(N, N)</span><br><span class="cl-a56b4d04">Simple Exponential Smoothing</span></p></td><td class="cl-a56eac80"><p class="cl-a56e9415"><span class="cl-a56b4d04">(N, A)</span></p></td><td class="cl-a56eac88"><p class="cl-a56e9415"><span class="cl-a56b4d04">(N, M)</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-a56eac92"><p class="cl-a56e9415"><span class="cl-a56b4d04">Additive (A)</span></p></td><td class="cl-a56eac93"><p class="cl-a56e9415"><span class="cl-a56b4d04">(A, N)</span><br><span class="cl-a56b4d04">Holt’s Linear</span></p></td><td class="cl-a56eac94"><p class="cl-a56e9415"><span class="cl-a56b4d04">(A, A)</span><br><span class="cl-a56b4d04">Additive Holt-Winters</span></p></td><td class="cl-a56eac9c"><p class="cl-a56e9415"><span class="cl-a56b4d04">(A, M)</span><br><span class="cl-a56b4d04">Multiplicative Holt-Winters</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-a56eac9d"><p class="cl-a56e9415"><span class="cl-a56b4d04">Additive Damped (Ad)</span></p></td><td class="cl-a56eac9e"><p class="cl-a56e9415"><span class="cl-a56b4d04">(Ad, N)</span><br><span class="cl-a56b4d04">Additive damped trend</span></p></td><td class="cl-a56eac9f"><p class="cl-a56e9415"><span class="cl-a56b4d04">(Ad, A)</span></p></td><td class="cl-a56eaca0"><p class="cl-a56e9415"><span class="cl-a56b4d04">(Ad, M)</span><br><span class="cl-a56b4d04">Holt-Winters Damped</span></p></td></tr></tbody></table></div>
<ul>
<li><p>There can be no trend (N), an additive (A) linear trend from the forecast horizon, or a damped additive (A<sub>d</sub>) trend leveling off from the forecast horizon.<a href="#fn1" class="footnote-ref" id="fnref1"><sup>1</sup></a></p></li>
<li><p>There can be no seasonality (N), or it can be additive (A) or multiplicative (M).</p></li>
</ul>
<p>The trend and seasonal combinations produce 3 x 3 = 9 possible exponential smoothing methods. ETS (Error, Trend, and Seasonality) models double the number of possible <em>state space models</em> to 18 by treating the error variances as either additive (A) or multiplicative (M). ETS models do not just extend the exponential smoothing models; they also estimate their parameters differently, using maximum likelihood estimation. For models with additive errors, this is equivalent to minimizing the sum of squared errors (SSE). The great advantage of using ETS models is that you can optimize the parameter settings by minimizing the Akaike Information Criterion (AIC<sub>c</sub>).</p>
<p><code>fable::ETS()</code> fits ETS models:</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="exponential.html#cb2-1" tabindex="-1"></a><span class="fu">ETS</span>(y <span class="sc">~</span> <span class="fu">error</span>(<span class="fu">c</span>(<span class="st">&quot;A&quot;</span>, <span class="st">&quot;M&quot;</span>)) <span class="sc">+</span> <span class="fu">trend</span>(<span class="fu">c</span>(<span class="st">&quot;N&quot;</span>, <span class="st">&quot;A&quot;</span>, <span class="st">&quot;Ad&quot;</span>)) <span class="sc">+</span> <span class="fu">season</span>(<span class="fu">c</span>(<span class="st">&quot;N&quot;</span>, <span class="st">&quot;A&quot;</span>, <span class="st">&quot;M&quot;</span>))</span></code></pre></div>
<div id="simple-exponential-smoothing-ses" class="section level2 hasAnchor" number="4.1">
<h2><span class="header-section-number">4.1</span> Simple Exponential Smoothing (SES)<a href="exponential.html#simple-exponential-smoothing-ses" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Simple exponential smoothing models (SES) have no seasonal or trend components. They are of the form <span class="math inline">\(\hat{y}_{T+h|T} = \alpha(1-\alpha)^0 y_{T-0} + \alpha(1-\alpha)^1y_{T-1} + \alpha(1-\alpha)^2y_{T-2} \dots\)</span> where <span class="math inline">\(0 &lt; \alpha &lt; 1\)</span> is a weighting parameter. On the one extreme, <span class="math inline">\(\alpha\)</span> = 1 is the same as a naive model. On the other extreme <span class="math inline">\(\alpha \approx\)</span> 0 is the average model.</p>
<p>ETS models are commonly expressed in component form as a recursive model. The component form of SES is</p>
<p><span class="math display">\[
\begin{align}
\hat{y}_{t+h|t} &amp;= l_t \\
l_t &amp;= \alpha y_t + (1 - \alpha)l_{t-1}
\end{align}
\]</span></p>
<p>The first component, <span class="math inline">\(\hat{y}_{t+h|t}\)</span>, is the forecast. It equals the last value of the estimated level. The second component, <span class="math inline">\(l_t\)</span>, is the level (or smoothed value) of the series at time <span class="math inline">\(t\)</span>. It describes how the level changes over time, kind of like a slope. ETS uses nonlinear optimization to estimate two parameters for SES, <span class="math inline">\(\alpha\)</span> and <span class="math inline">\(l_0\)</span>.</p>
<div id="example" class="section level4 unnumbered hasAnchor">
<h4>Example<a href="exponential.html#example" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Data set <code>tsibbledata::global_economy</code> contains annual country-level economic indicators, including <code>Exports</code>. This time series has no trend or seasonality, so it is a good candidate for SES.</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="exponential.html#cb3-1" tabindex="-1"></a>tsibbledata<span class="sc">::</span>global_economy <span class="sc">%&gt;%</span></span>
<span id="cb3-2"><a href="exponential.html#cb3-2" tabindex="-1"></a>  <span class="fu">filter</span>(Country <span class="sc">==</span> <span class="st">&quot;Algeria&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb3-3"><a href="exponential.html#cb3-3" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> Year, <span class="at">y =</span> Exports)) <span class="sc">+</span></span>
<span id="cb3-4"><a href="exponential.html#cb3-4" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb3-5"><a href="exponential.html#cb3-5" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Algerian Exports (% of GDP)&quot;</span>)</span></code></pre></div>
<p><img src="time-series_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<p><code>fable::ETS()</code> is the exponential smoothing function. With additive errors, this is an ETS(A, N, N) model.</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="exponential.html#cb4-1" tabindex="-1"></a>ses_fit <span class="ot">&lt;-</span> tsibbledata<span class="sc">::</span>global_economy <span class="sc">%&gt;%</span></span>
<span id="cb4-2"><a href="exponential.html#cb4-2" tabindex="-1"></a>  <span class="fu">filter</span>(Country <span class="sc">==</span> <span class="st">&quot;Algeria&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb4-3"><a href="exponential.html#cb4-3" tabindex="-1"></a>  <span class="fu">model</span>(<span class="fu">ETS</span>(Exports <span class="sc">~</span> <span class="fu">error</span>(<span class="st">&quot;A&quot;</span>) <span class="sc">+</span> <span class="fu">trend</span>(<span class="st">&quot;N&quot;</span>) <span class="sc">+</span> <span class="fu">season</span>(<span class="st">&quot;N&quot;</span>)))</span>
<span id="cb4-4"><a href="exponential.html#cb4-4" tabindex="-1"></a></span>
<span id="cb4-5"><a href="exponential.html#cb4-5" tabindex="-1"></a>ses_fit <span class="sc">%&gt;%</span> <span class="fu">report</span>()</span></code></pre></div>
<pre><code>## Series: Exports 
## Model: ETS(A,N,N) 
##   Smoothing parameters:
##     alpha = 0.8399875 
## 
##   Initial states:
##    l[0]
##  39.539
## 
##   sigma^2:  35.6301
## 
##      AIC     AICc      BIC 
## 446.7154 447.1599 452.8968</code></pre>
<p>Exports were <span class="math inline">\(\hat{l}_0\)</span> = 39.5% of GDP at period 0 (1960). <span class="math inline">\(\hat{\alpha}\)</span> = 0.840, a high weight on recent values. Check the model assumptions with residuals plots.</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="exponential.html#cb6-1" tabindex="-1"></a><span class="fu">gg_tsresiduals</span>(ses_fit)</span></code></pre></div>
<p><img src="time-series_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<p>Residual heteroscedasticity compromises prediction intervals. The innovation residuals vs time plot shows no heteroscedasticity.<a href="#fn2" class="footnote-ref" id="fnref2"><sup>2</sup></a> It does show a potential outlier around 1962 which might be a concern. Autocorrelation increases prediction intervals. The autocorrelation function plot shows a barely significant negative spike at lag 12 years. Non-normal residuals also compromise prediction intervals. The residual distribution in the histogram is slightly left-skewed.</p>
<p>Use the fitted model to forecast the response variable for five periods. <code>hilo()</code> attaches a prediction interval to the tsibble.</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="exponential.html#cb7-1" tabindex="-1"></a>ses_fc <span class="ot">&lt;-</span> ses_fit <span class="sc">%&gt;%</span></span>
<span id="cb7-2"><a href="exponential.html#cb7-2" tabindex="-1"></a>  <span class="fu">forecast</span>(<span class="at">h =</span> <span class="dv">5</span>) <span class="sc">%&gt;%</span></span>
<span id="cb7-3"><a href="exponential.html#cb7-3" tabindex="-1"></a>  <span class="fu">hilo</span>(<span class="dv">80</span>) <span class="sc">%&gt;%</span></span>
<span id="cb7-4"><a href="exponential.html#cb7-4" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb7-5"><a href="exponential.html#cb7-5" tabindex="-1"></a>    <span class="at">lpi =</span> <span class="fu">map_dbl</span>(<span class="st">`</span><span class="at">80%</span><span class="st">`</span>, <span class="sc">~</span>.<span class="sc">$</span>lower),</span>
<span id="cb7-6"><a href="exponential.html#cb7-6" tabindex="-1"></a>    <span class="at">upi =</span> <span class="fu">map_dbl</span>(<span class="st">`</span><span class="at">80%</span><span class="st">`</span>, <span class="sc">~</span>.<span class="sc">$</span>upper)</span>
<span id="cb7-7"><a href="exponential.html#cb7-7" tabindex="-1"></a>  )</span>
<span id="cb7-8"><a href="exponential.html#cb7-8" tabindex="-1"></a></span>
<span id="cb7-9"><a href="exponential.html#cb7-9" tabindex="-1"></a>ses_fit <span class="sc">%&gt;%</span></span>
<span id="cb7-10"><a href="exponential.html#cb7-10" tabindex="-1"></a>  <span class="fu">augment</span>() <span class="sc">%&gt;%</span></span>
<span id="cb7-11"><a href="exponential.html#cb7-11" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> Year)) <span class="sc">+</span></span>
<span id="cb7-12"><a href="exponential.html#cb7-12" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> Exports)) <span class="sc">+</span></span>
<span id="cb7-13"><a href="exponential.html#cb7-13" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> .fitted), <span class="at">color =</span> <span class="st">&quot;goldenrod&quot;</span>) <span class="sc">+</span></span>
<span id="cb7-14"><a href="exponential.html#cb7-14" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">data =</span> ses_fc, <span class="fu">aes</span>(<span class="at">y =</span> .mean), <span class="at">color =</span> <span class="st">&quot;goldenrod&quot;</span>) <span class="sc">+</span></span>
<span id="cb7-15"><a href="exponential.html#cb7-15" tabindex="-1"></a>  <span class="fu">geom_ribbon</span>(<span class="at">data =</span> ses_fc, <span class="fu">aes</span>(<span class="at">ymin =</span> lpi, <span class="at">ymax =</span> upi), <span class="at">alpha =</span> <span class="fl">0.2</span>, <span class="at">fill =</span> <span class="st">&quot;goldenrod&quot;</span>) <span class="sc">+</span></span>
<span id="cb7-16"><a href="exponential.html#cb7-16" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Simple Exponential Smoothing, ETS(A, N, N)&quot;</span>)</span></code></pre></div>
<p><img src="time-series_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
</div>
</div>
<div id="holt-linear" class="section level2 hasAnchor" number="4.2">
<h2><span class="header-section-number">4.2</span> Holt Linear<a href="exponential.html#holt-linear" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Holt’s linear method extends SES with a trend component, <span class="math inline">\(b_t\)</span>.</p>
<p><span class="math display">\[
\begin{align}
\hat{y}_{t+h|t} &amp;= l_t + hb_t \\
l_t &amp;= \alpha y_t + (1 - \alpha)(l_{t-1} + hb_{t-1}) \\
b_t &amp;= \beta^*(l_t - l_{t-1}) + (1 - \beta^*)b_{t-1}
\end{align}
\]</span></p>
<p>The level equation, <span class="math inline">\(l_t\)</span>, is like SES except for a trend adjustment. The trend equation, <span class="math inline">\(b_t\)</span>, describes how the slope changes over time. The parameter <span class="math inline">\(\beta^*\)</span> describes how quickly the slope can change. Now there are four parameter to estimate, <span class="math inline">\(\alpha\)</span>, <span class="math inline">\(l_0\)</span>, <span class="math inline">\(\beta^*\)</span>, and <span class="math inline">\(b_0\)</span>.</p>
<div id="example-1" class="section level4 unnumbered hasAnchor">
<h4>Example<a href="exponential.html#example-1" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Data set <code>tsibbledata::global_economy</code> contains annual country-level economic indicators, including <code>Population</code> size. This time series has a trend, so it is a good candidate for Holt’s linear trend method.</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="exponential.html#cb8-1" tabindex="-1"></a>tsibbledata<span class="sc">::</span>global_economy <span class="sc">%&gt;%</span></span>
<span id="cb8-2"><a href="exponential.html#cb8-2" tabindex="-1"></a>  <span class="fu">filter</span>(Country <span class="sc">==</span> <span class="st">&quot;Australia&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb8-3"><a href="exponential.html#cb8-3" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> Year, <span class="at">y =</span> Population)) <span class="sc">+</span></span>
<span id="cb8-4"><a href="exponential.html#cb8-4" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb8-5"><a href="exponential.html#cb8-5" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Australian Population.&quot;</span>)</span></code></pre></div>
<p><img src="time-series_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<p>Fit the model with <code>ETS()</code> specifying an additive trend, ETS(A, A, N).</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="exponential.html#cb9-1" tabindex="-1"></a>holt_fit <span class="ot">&lt;-</span> tsibbledata<span class="sc">::</span>global_economy <span class="sc">%&gt;%</span></span>
<span id="cb9-2"><a href="exponential.html#cb9-2" tabindex="-1"></a>  <span class="fu">filter</span>(Country <span class="sc">==</span> <span class="st">&quot;Australia&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb9-3"><a href="exponential.html#cb9-3" tabindex="-1"></a>  <span class="fu">model</span>(<span class="fu">ETS</span>(Population <span class="sc">~</span> <span class="fu">error</span>(<span class="st">&quot;A&quot;</span>) <span class="sc">+</span> <span class="fu">trend</span>(<span class="st">&quot;A&quot;</span>) <span class="sc">+</span> <span class="fu">season</span>(<span class="st">&quot;N&quot;</span>)))</span>
<span id="cb9-4"><a href="exponential.html#cb9-4" tabindex="-1"></a></span>
<span id="cb9-5"><a href="exponential.html#cb9-5" tabindex="-1"></a>holt_fit <span class="sc">%&gt;%</span> <span class="fu">report</span>()</span></code></pre></div>
<pre><code>## Series: Population 
## Model: ETS(A,A,N) 
##   Smoothing parameters:
##     alpha = 0.9998992 
##     beta  = 0.3257153 
## 
##   Initial states:
##      l[0]     b[0]
##  10067191 228012.5
## 
##   sigma^2:  4139605871
## 
##      AIC     AICc      BIC 
## 1525.705 1526.859 1536.008</code></pre>
<p><span class="math inline">\(\hat{l}_0\)</span> = 10,067,191 people at period 0 (1960). <span class="math inline">\(\alpha\)</span> is high when the trend increases rapidly, assigning more weight to recent values. <span class="math inline">\(\hat{\alpha}\)</span> = 0.9999, a very high weighting. Population initially grows at <span class="math inline">\(\beta_0\)</span> = 228,013 people per year. <span class="math inline">\(\hat{\beta}\)</span> = 0.326, a fairly large value, meaning the trend changes often.</p>
<p>Check the model assumptions with residuals plots. There is no heteroscedasticity in the residuals vs time plot and no skew in the residual distribution plot, so the prediction intervals are reliable. The autocorrelation plot has no significant spikes, so the prediction intervals will not be unduly large.</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="exponential.html#cb11-1" tabindex="-1"></a><span class="fu">gg_tsresiduals</span>(holt_fit)</span></code></pre></div>
<p><img src="time-series_files/figure-html/unnamed-chunk-11-1.png" width="672" /></p>
<p>Use the fitted model to forecast the response variable for ten periods.</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="exponential.html#cb12-1" tabindex="-1"></a>holt_fc <span class="ot">&lt;-</span> holt_fit <span class="sc">%&gt;%</span></span>
<span id="cb12-2"><a href="exponential.html#cb12-2" tabindex="-1"></a>  <span class="fu">forecast</span>(<span class="at">h =</span> <span class="dv">10</span>) <span class="sc">%&gt;%</span></span>
<span id="cb12-3"><a href="exponential.html#cb12-3" tabindex="-1"></a>  <span class="fu">hilo</span>(<span class="dv">80</span>) <span class="sc">%&gt;%</span></span>
<span id="cb12-4"><a href="exponential.html#cb12-4" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb12-5"><a href="exponential.html#cb12-5" tabindex="-1"></a>    <span class="at">lpi =</span> <span class="fu">map_dbl</span>(<span class="st">`</span><span class="at">80%</span><span class="st">`</span>, <span class="sc">~</span>.<span class="sc">$</span>lower),</span>
<span id="cb12-6"><a href="exponential.html#cb12-6" tabindex="-1"></a>    <span class="at">upi =</span> <span class="fu">map_dbl</span>(<span class="st">`</span><span class="at">80%</span><span class="st">`</span>, <span class="sc">~</span>.<span class="sc">$</span>upper)</span>
<span id="cb12-7"><a href="exponential.html#cb12-7" tabindex="-1"></a>  )</span>
<span id="cb12-8"><a href="exponential.html#cb12-8" tabindex="-1"></a></span>
<span id="cb12-9"><a href="exponential.html#cb12-9" tabindex="-1"></a>holt_fit <span class="sc">%&gt;%</span></span>
<span id="cb12-10"><a href="exponential.html#cb12-10" tabindex="-1"></a>  <span class="fu">augment</span>() <span class="sc">%&gt;%</span></span>
<span id="cb12-11"><a href="exponential.html#cb12-11" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> Year)) <span class="sc">+</span></span>
<span id="cb12-12"><a href="exponential.html#cb12-12" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> Population)) <span class="sc">+</span></span>
<span id="cb12-13"><a href="exponential.html#cb12-13" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> .fitted), <span class="at">color =</span> <span class="st">&quot;goldenrod&quot;</span>) <span class="sc">+</span></span>
<span id="cb12-14"><a href="exponential.html#cb12-14" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">data =</span> holt_fc, <span class="fu">aes</span>(<span class="at">y =</span> .mean), <span class="at">color =</span> <span class="st">&quot;goldenrod&quot;</span>) <span class="sc">+</span></span>
<span id="cb12-15"><a href="exponential.html#cb12-15" tabindex="-1"></a>  <span class="fu">geom_ribbon</span>(<span class="at">data =</span> holt_fc, <span class="fu">aes</span>(<span class="at">ymin =</span> lpi, <span class="at">ymax =</span> upi), <span class="at">alpha =</span> <span class="fl">0.2</span>, <span class="at">fill =</span> <span class="st">&quot;goldenrod&quot;</span>) <span class="sc">+</span></span>
<span id="cb12-16"><a href="exponential.html#cb12-16" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Holt&#39;s Linear Method, ETS(A, A, N)&quot;</span>)</span></code></pre></div>
<p><img src="time-series_files/figure-html/unnamed-chunk-12-1.png" width="672" /></p>
</div>
</div>
<div id="additive-damped-trend" class="section level2 hasAnchor" number="4.3">
<h2><span class="header-section-number">4.3</span> Additive Damped Trend<a href="exponential.html#additive-damped-trend" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Holt’s linear trend produces a sloped, but straight, line. Research shows that constant trends tend to overshoot. The additive damped trend model introduces a damping parameter, <span class="math inline">\(\phi\)</span>, to reduce the forecasted trend to a flat line over time. The forecast equation replaces <span class="math inline">\(h\)</span> with the series <span class="math inline">\(\phi^1 + \phi^2 + \cdots + \phi^h\)</span>. The trend equation adds <span class="math inline">\(\phi\)</span> as a multiplier to the second term.</p>
<p><span class="math display">\[
\begin{align}
\hat{y}_{t+h|t} &amp;= l_t + (\phi^1 + \phi^2 + \cdots + \phi^h)b_t \\
l_t &amp;= \alpha y_t + (1 - \alpha)(l_{t-1} + \phi b_{t-1}) \\
b_t &amp;= \beta^*(l_t - l_{t-1}) + (1 - \beta^*) \phi b_{t-1}
\end{align}
\]</span></p>
<p>Now there are five parameters to estimate, <span class="math inline">\(\alpha\)</span>, <span class="math inline">\(\beta^*\)</span>, <span class="math inline">\(l_0\)</span>, <span class="math inline">\(b_0\)</span>, and <span class="math inline">\(\phi\)</span> (although you can supply a <span class="math inline">\(\phi\)</span> value to the <code>trend()</code> equation. Expect <span class="math inline">\(\phi\)</span> to between .8 and .998.</p>
<div id="example-2" class="section level4 unnumbered hasAnchor">
<h4>Example<a href="exponential.html#example-2" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Return to the Australian population data and include an additive damped trend model in a fit. The new model is an ETS(A, A<sub>d</sub>, N).</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="exponential.html#cb13-1" tabindex="-1"></a>dholt_fit <span class="ot">&lt;-</span> tsibbledata<span class="sc">::</span>global_economy <span class="sc">%&gt;%</span></span>
<span id="cb13-2"><a href="exponential.html#cb13-2" tabindex="-1"></a>  <span class="fu">filter</span>(Country <span class="sc">==</span> <span class="st">&quot;Australia&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb13-3"><a href="exponential.html#cb13-3" tabindex="-1"></a>  <span class="fu">model</span>(</span>
<span id="cb13-4"><a href="exponential.html#cb13-4" tabindex="-1"></a>    <span class="st">`</span><span class="at">Holt&#39;s Linear</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">ETS</span>(Population <span class="sc">~</span> <span class="fu">error</span>(<span class="st">&quot;A&quot;</span>) <span class="sc">+</span> <span class="fu">trend</span>(<span class="st">&quot;A&quot;</span>) <span class="sc">+</span> <span class="fu">season</span>(<span class="st">&quot;N&quot;</span>)),</span>
<span id="cb13-5"><a href="exponential.html#cb13-5" tabindex="-1"></a>    <span class="st">`</span><span class="at">Damped Holt&#39;s Linear</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">ETS</span>(Population <span class="sc">~</span> <span class="fu">error</span>(<span class="st">&quot;A&quot;</span>) <span class="sc">+</span> <span class="fu">trend</span>(<span class="st">&quot;Ad&quot;</span>) <span class="sc">+</span> <span class="fu">season</span>(<span class="st">&quot;N&quot;</span>))</span>
<span id="cb13-6"><a href="exponential.html#cb13-6" tabindex="-1"></a>  )</span>
<span id="cb13-7"><a href="exponential.html#cb13-7" tabindex="-1"></a></span>
<span id="cb13-8"><a href="exponential.html#cb13-8" tabindex="-1"></a><span class="co"># Just report on the new model.</span></span>
<span id="cb13-9"><a href="exponential.html#cb13-9" tabindex="-1"></a>dholt_fit <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="st">`</span><span class="at">Damped Holt&#39;s Linear</span><span class="st">`</span>) <span class="sc">%&gt;%</span> <span class="fu">report</span>()</span></code></pre></div>
<pre><code>## Series: Population 
## Model: ETS(A,Ad,N) 
##   Smoothing parameters:
##     alpha = 0.9998988 
##     beta  = 0.4392868 
##     phi   = 0.98 
## 
##   Initial states:
##      l[0]     b[0]
##  10067191 277729.2
## 
##   sigma^2:  4584582964
## 
##      AIC     AICc      BIC 
## 1532.543 1534.190 1544.906</code></pre>
<p><span class="math inline">\(\hat{\phi}\)</span> = 0.980, a modest amount of damping. <span class="math inline">\(\hat{\beta}\)</span> increased from 0.326 in the linear model to 0.439 here, so the slope is changing more frequently.</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="exponential.html#cb15-1" tabindex="-1"></a>dholt_fc <span class="ot">&lt;-</span> dholt_fit <span class="sc">%&gt;%</span></span>
<span id="cb15-2"><a href="exponential.html#cb15-2" tabindex="-1"></a>  <span class="fu">forecast</span>(<span class="at">h =</span> <span class="dv">10</span>) <span class="sc">%&gt;%</span></span>
<span id="cb15-3"><a href="exponential.html#cb15-3" tabindex="-1"></a>  <span class="fu">hilo</span>(<span class="dv">80</span>) <span class="sc">%&gt;%</span></span>
<span id="cb15-4"><a href="exponential.html#cb15-4" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb15-5"><a href="exponential.html#cb15-5" tabindex="-1"></a>    <span class="at">lpi =</span> <span class="fu">map_dbl</span>(<span class="st">`</span><span class="at">80%</span><span class="st">`</span>, <span class="sc">~</span>.<span class="sc">$</span>lower),</span>
<span id="cb15-6"><a href="exponential.html#cb15-6" tabindex="-1"></a>    <span class="at">upi =</span> <span class="fu">map_dbl</span>(<span class="st">`</span><span class="at">80%</span><span class="st">`</span>, <span class="sc">~</span>.<span class="sc">$</span>upper)</span>
<span id="cb15-7"><a href="exponential.html#cb15-7" tabindex="-1"></a>  )</span>
<span id="cb15-8"><a href="exponential.html#cb15-8" tabindex="-1"></a></span>
<span id="cb15-9"><a href="exponential.html#cb15-9" tabindex="-1"></a>palette_dholt <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">`</span><span class="at">Holt&#39;s Linear</span><span class="st">`</span> <span class="ot">=</span> <span class="st">&quot;goldenrod&quot;</span>, <span class="st">`</span><span class="at">Damped Holt&#39;s Linear</span><span class="st">`</span> <span class="ot">=</span> <span class="st">&quot;seagreen&quot;</span>)</span>
<span id="cb15-10"><a href="exponential.html#cb15-10" tabindex="-1"></a></span>
<span id="cb15-11"><a href="exponential.html#cb15-11" tabindex="-1"></a>dholt_fit <span class="sc">%&gt;%</span></span>
<span id="cb15-12"><a href="exponential.html#cb15-12" tabindex="-1"></a>  <span class="fu">augment</span>() <span class="sc">%&gt;%</span></span>
<span id="cb15-13"><a href="exponential.html#cb15-13" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> Year)) <span class="sc">+</span></span>
<span id="cb15-14"><a href="exponential.html#cb15-14" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> Population)) <span class="sc">+</span></span>
<span id="cb15-15"><a href="exponential.html#cb15-15" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> .fitted, <span class="at">color =</span> .model)) <span class="sc">+</span></span>
<span id="cb15-16"><a href="exponential.html#cb15-16" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">data =</span> dholt_fc, <span class="fu">aes</span>(<span class="at">y =</span> .mean, <span class="at">color =</span> .model)) <span class="sc">+</span></span>
<span id="cb15-17"><a href="exponential.html#cb15-17" tabindex="-1"></a>  <span class="fu">geom_ribbon</span>(<span class="at">data =</span> dholt_fc, <span class="fu">aes</span>(<span class="at">ymin =</span> lpi, <span class="at">ymax =</span> upi, <span class="at">color =</span> .model, <span class="at">fill =</span> .model), </span>
<span id="cb15-18"><a href="exponential.html#cb15-18" tabindex="-1"></a>              <span class="at">alpha =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb15-19"><a href="exponential.html#cb15-19" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> palette_dholt) <span class="sc">+</span></span>
<span id="cb15-20"><a href="exponential.html#cb15-20" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> palette_dholt) <span class="sc">+</span></span>
<span id="cb15-21"><a href="exponential.html#cb15-21" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">&quot;top&quot;</span>) <span class="sc">+</span></span>
<span id="cb15-22"><a href="exponential.html#cb15-22" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">color =</span> <span class="cn">NULL</span>, <span class="at">fill =</span> <span class="cn">NULL</span>, </span>
<span id="cb15-23"><a href="exponential.html#cb15-23" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">&quot;Holt&#39;s Linear Method, ETS(A, A, N), and Additive Damped, ETS(A, Ad, N)&quot;</span>)</span></code></pre></div>
<p><img src="time-series_files/figure-html/unnamed-chunk-14-1.png" width="672" /></p>
</div>
</div>
<div id="holt-winters" class="section level2 hasAnchor" number="4.4">
<h2><span class="header-section-number">4.4</span> Holt-Winters<a href="exponential.html#holt-winters" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The Holt-Winters method extends Holt’s method with a seasonality component, <span class="math inline">\(s_t\)</span>, for <span class="math inline">\(m\)</span> seasons per period. There are two versions of this model, the <em>additive</em> and the <em>multiplicative</em>. The additive method assumes the error variance is constant, and the seasonal component sums to approximately zero over the course of the year. The multiplicative version assumes the error variance scales with the level, and the seasonal component sums to approximately <span class="math inline">\(m\)</span> over the course of the year.</p>
<p><strong>Additive Holt-Winters</strong> introduces the seasonality component as an additive element.</p>
<p><span class="math display">\[
\begin{align}
\hat{y}_{t+h|t} &amp;= l_t + hb_t + s_{t+h-m(k+1)} \\
l_t &amp;= \alpha(y_t - s_{t-m}) + (1 - \alpha)(l_{t-1} + b_{t-1}) \\
b_t &amp;= \beta^*(l_t - l_{t-1}) + (1 - \beta^*)b_{t-1} \\
s_t &amp;= \gamma(y_t - l_{t-1} - b_{t-1}) + (1 - \gamma)s_{t-m}
\end{align}
\]</span></p>
<p><span class="math inline">\(k\)</span> is the modulus of <span class="math inline">\((h - 1) / m\)</span>, so <span class="math inline">\(s_{t+h-m(k+1)}\)</span> is always based on the prior seasonal period. <span class="math inline">\(l_t\)</span> is a weighted average (<span class="math inline">\(\alpha\)</span> weighting) between the seasonally adjusted observation and the non-seasonal forecast. The trend component is unchanged. The seasonal component is a weighted average (<span class="math inline">\(\gamma\)</span> weighting) between the current seasonal index and the same season of the prior season period.</p>
<p>The seasonality averages to one in <strong>multiplicative Holt-Winters</strong>. Use the multiplicative method if the seasonal variation increases with the level.</p>
<p><span class="math display">\[
\begin{align}
\hat{y}_{t+h|t} &amp;= (l_t + hb_t) s_{t+h-m(k+1)} \\
l_t &amp;= \alpha\frac{y_t}{s_{t-m}} + (1 - \alpha)(l_{t-1} + b_{t-1}) \\
b_t &amp;= \beta^*(l_t - l_{t-1}) + (1-\beta*)b_{t-1} \\
s_t &amp;= \gamma\frac{y_t}{(l_{t-1} - b_{t-1})} + (1 - \gamma)s_{t-m} \\
\end{align}
\]</span></p>
<p>Now there are five smoothing parameters to estimate: <span class="math inline">\(\alpha\)</span>, <span class="math inline">\(l_0\)</span>, <span class="math inline">\(\beta^*\)</span>, <span class="math inline">\(b_0\)</span>, and <span class="math inline">\(\gamma\)</span>, plus an initial value for each season of the seasonal period.</p>
<div id="example-3" class="section level4 unnumbered hasAnchor">
<h4>Example<a href="exponential.html#example-3" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Data set <code>tsibble::tourism</code> contains quarterly domestic tourist visit-nights in Australia. It’s not clear whether the error variance increases with the series level, so either the additive or the multiplicative method may be appropriate.</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="exponential.html#cb16-1" tabindex="-1"></a>tsibble<span class="sc">::</span>tourism <span class="sc">%&gt;%</span></span>
<span id="cb16-2"><a href="exponential.html#cb16-2" tabindex="-1"></a>  <span class="fu">filter</span>(Purpose <span class="sc">==</span> <span class="st">&quot;Holiday&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb16-3"><a href="exponential.html#cb16-3" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">Trips =</span> <span class="fu">sum</span>(Trips) <span class="sc">/</span> <span class="dv">1000</span>) <span class="sc">%&gt;%</span></span>
<span id="cb16-4"><a href="exponential.html#cb16-4" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> Quarter, <span class="at">y =</span> Trips)) <span class="sc">+</span></span>
<span id="cb16-5"><a href="exponential.html#cb16-5" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb16-6"><a href="exponential.html#cb16-6" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Australian Domestic Tourist Visit-Nights&quot;</span>)</span></code></pre></div>
<p><img src="time-series_files/figure-html/unnamed-chunk-15-1.png" width="672" /></p>
<p>Fit the model with <code>ETS()</code> specifying additive and multiplicative seasonality and error, ETS(A, A, A) and ETS(M, A, M).</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="exponential.html#cb17-1" tabindex="-1"></a>hw_fit <span class="ot">&lt;-</span> tsibble<span class="sc">::</span>tourism <span class="sc">%&gt;%</span></span>
<span id="cb17-2"><a href="exponential.html#cb17-2" tabindex="-1"></a>  <span class="fu">filter</span>(Purpose <span class="sc">==</span> <span class="st">&quot;Holiday&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb17-3"><a href="exponential.html#cb17-3" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">Trips =</span> <span class="fu">sum</span>(Trips) <span class="sc">/</span> <span class="dv">1000</span>) <span class="sc">%&gt;%</span></span>
<span id="cb17-4"><a href="exponential.html#cb17-4" tabindex="-1"></a>  <span class="fu">model</span>(</span>
<span id="cb17-5"><a href="exponential.html#cb17-5" tabindex="-1"></a>    <span class="st">`</span><span class="at">Additive Holt-Winters</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">ETS</span>(Trips <span class="sc">~</span> <span class="fu">error</span>(<span class="st">&quot;A&quot;</span>) <span class="sc">+</span> <span class="fu">trend</span>(<span class="st">&quot;A&quot;</span>) <span class="sc">+</span> <span class="fu">season</span>(<span class="st">&quot;A&quot;</span>)),</span>
<span id="cb17-6"><a href="exponential.html#cb17-6" tabindex="-1"></a>    <span class="st">`</span><span class="at">Multiplicative Holt-Winters</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">ETS</span>(Trips <span class="sc">~</span> <span class="fu">error</span>(<span class="st">&quot;M&quot;</span>) <span class="sc">+</span> <span class="fu">trend</span>(<span class="st">&quot;A&quot;</span>) <span class="sc">+</span> <span class="fu">season</span>(<span class="st">&quot;M&quot;</span>))</span>
<span id="cb17-7"><a href="exponential.html#cb17-7" tabindex="-1"></a>  )</span>
<span id="cb17-8"><a href="exponential.html#cb17-8" tabindex="-1"></a></span>
<span id="cb17-9"><a href="exponential.html#cb17-9" tabindex="-1"></a>hw_fit <span class="sc">%&gt;%</span> <span class="fu">tidy</span>() <span class="sc">%&gt;%</span> <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> .model, <span class="at">values_from =</span> estimate)</span></code></pre></div>
<pre><code>## # A tibble: 9 × 3
##   term  `Additive Holt-Winters` `Multiplicative Holt-Winters`
##   &lt;chr&gt;                   &lt;dbl&gt;                         &lt;dbl&gt;
## 1 alpha                0.262                         0.224   
## 2 beta                 0.0431                        0.0304  
## 3 gamma                0.000100                      0.000100
## 4 l[0]                 9.79                         10.0     
## 5 b[0]                 0.0211                       -0.0114  
## 6 s[0]                -0.534                         0.943   
## 7 s[-1]               -0.670                         0.927   
## 8 s[-2]               -0.294                         0.969   
## 9 s[-3]                1.50                          1.16</code></pre>
<p>Notice that the seasonal component estimates, <code>s[0]</code> to <code>s[-3]</code>, sum to ~0 for the additive model and ~4 for the multiplicative model, the number of seasons in the seasonal period. The small <span class="math inline">\(\hat{\gamma}\)</span> values mean the seasonal component hardly changes over time. The small <span class="math inline">\(\hat{\beta}\)</span> values mean the slope component hardly changes over time. You can see this more clearly in the fit decomposition (note the differing vertical scales for the slope and level components).</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="exponential.html#cb19-1" tabindex="-1"></a>hw_fit <span class="sc">%&gt;%</span> </span>
<span id="cb19-2"><a href="exponential.html#cb19-2" tabindex="-1"></a>  <span class="fu">components</span>() <span class="sc">%&gt;%</span></span>
<span id="cb19-3"><a href="exponential.html#cb19-3" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="at">cols =</span> Trips<span class="sc">:</span>remainder) <span class="sc">%&gt;%</span></span>
<span id="cb19-4"><a href="exponential.html#cb19-4" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">name =</span> <span class="fu">factor</span>(name, <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">&quot;Trips&quot;</span>, <span class="st">&quot;level&quot;</span>, <span class="st">&quot;slope&quot;</span>, <span class="st">&quot;season&quot;</span>, <span class="st">&quot;remainder&quot;</span>))) <span class="sc">%&gt;%</span></span>
<span id="cb19-5"><a href="exponential.html#cb19-5" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> Quarter, <span class="at">y =</span> value)) <span class="sc">+</span></span>
<span id="cb19-6"><a href="exponential.html#cb19-6" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb19-7"><a href="exponential.html#cb19-7" tabindex="-1"></a>  <span class="fu">facet_grid</span>(<span class="at">rows =</span> <span class="fu">vars</span>(name), <span class="at">cols =</span> <span class="fu">vars</span>(.model), <span class="at">scales =</span> <span class="st">&quot;free_y&quot;</span>) <span class="sc">+</span></span>
<span id="cb19-8"><a href="exponential.html#cb19-8" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="cn">NULL</span>, <span class="at">y =</span> <span class="cn">NULL</span>, <span class="at">title =</span> <span class="st">&quot;Holt-Winters Fit Decomposition&quot;</span>)</span></code></pre></div>
<p><img src="time-series_files/figure-html/unnamed-chunk-17-1.png" width="672" /></p>
<p>The model fit metrics suggest Multiplicative Holt-Winters is the better model. It has lower AIC and MSE.</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="exponential.html#cb20-1" tabindex="-1"></a>hw_fit <span class="sc">%&gt;%</span> <span class="fu">glance</span>()</span></code></pre></div>
<pre><code>## # A tibble: 2 × 9
##   .model                     sigma2 log_lik   AIC  AICc   BIC   MSE  AMSE    MAE
##   &lt;chr&gt;                       &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;
## 1 Additive Holt-Winters     0.193     -105.  229.  231.  250. 0.174 0.184 0.321 
## 2 Multiplicative Holt-Wint… 0.00212   -104.  227.  229.  248. 0.170 0.183 0.0328</code></pre>
<p>Check the model assumptions of the multiplicative model. The residuals plot shows some heteroscedasticity in the middle periods, and higher variance the latter years. The histogram shows a normal distribution. The autocorrelation function (ACF) plot shows a single significant spike at t14. The Ljung-Box test fails to reject the null hypothesis of no autocorrelation of the residuals (<em>p</em> = 0.504).</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="exponential.html#cb22-1" tabindex="-1"></a><span class="co"># Can&#39;t use an object containing multiple fits, so re-fit just the multiplicative model.</span></span>
<span id="cb22-2"><a href="exponential.html#cb22-2" tabindex="-1"></a>hwm_fit <span class="ot">&lt;-</span> tsibble<span class="sc">::</span>tourism <span class="sc">%&gt;%</span></span>
<span id="cb22-3"><a href="exponential.html#cb22-3" tabindex="-1"></a>  <span class="fu">filter</span>(Purpose <span class="sc">==</span> <span class="st">&quot;Holiday&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb22-4"><a href="exponential.html#cb22-4" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">Trips =</span> <span class="fu">sum</span>(Trips) <span class="sc">/</span> <span class="dv">1000</span>) <span class="sc">%&gt;%</span></span>
<span id="cb22-5"><a href="exponential.html#cb22-5" tabindex="-1"></a>  <span class="fu">model</span>(<span class="fu">ETS</span>(Trips <span class="sc">~</span> <span class="fu">error</span>(<span class="st">&quot;M&quot;</span>) <span class="sc">+</span> <span class="fu">trend</span>(<span class="st">&quot;A&quot;</span>) <span class="sc">+</span> <span class="fu">season</span>(<span class="st">&quot;M&quot;</span>)))</span>
<span id="cb22-6"><a href="exponential.html#cb22-6" tabindex="-1"></a></span>
<span id="cb22-7"><a href="exponential.html#cb22-7" tabindex="-1"></a>hwm_fit <span class="sc">%&gt;%</span> </span>
<span id="cb22-8"><a href="exponential.html#cb22-8" tabindex="-1"></a>  <span class="fu">gg_tsresiduals</span>()</span></code></pre></div>
<p><img src="time-series_files/figure-html/unnamed-chunk-19-1.png" width="672" /></p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="exponential.html#cb23-1" tabindex="-1"></a>hwm_fit <span class="sc">%&gt;%</span></span>
<span id="cb23-2"><a href="exponential.html#cb23-2" tabindex="-1"></a>  <span class="fu">augment</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb23-3"><a href="exponential.html#cb23-3" tabindex="-1"></a>  <span class="fu">features</span>(<span class="at">.var =</span> .innov, <span class="at">features =</span> ljung_box, <span class="at">lag =</span> <span class="dv">14</span>)</span></code></pre></div>
<pre><code>## # A tibble: 1 × 3
##   .model                                                     lb_stat lb_pvalue
##   &lt;chr&gt;                                                        &lt;dbl&gt;     &lt;dbl&gt;
## 1 &quot;ETS(Trips ~ error(\&quot;M\&quot;) + trend(\&quot;A\&quot;) + season(\&quot;M\&quot;))&quot;    13.3     0.504</code></pre>
<p>Use the fitted model to forecast the response variable for ten periods.</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="exponential.html#cb25-1" tabindex="-1"></a>hw_fc <span class="ot">&lt;-</span> hw_fit <span class="sc">%&gt;%</span></span>
<span id="cb25-2"><a href="exponential.html#cb25-2" tabindex="-1"></a>  <span class="fu">forecast</span>(<span class="at">h =</span> <span class="dv">10</span>) <span class="sc">%&gt;%</span></span>
<span id="cb25-3"><a href="exponential.html#cb25-3" tabindex="-1"></a>  <span class="fu">hilo</span>(<span class="dv">80</span>) <span class="sc">%&gt;%</span></span>
<span id="cb25-4"><a href="exponential.html#cb25-4" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb25-5"><a href="exponential.html#cb25-5" tabindex="-1"></a>    <span class="at">lpi =</span> <span class="fu">map_dbl</span>(<span class="st">`</span><span class="at">80%</span><span class="st">`</span>, <span class="sc">~</span>.<span class="sc">$</span>lower),</span>
<span id="cb25-6"><a href="exponential.html#cb25-6" tabindex="-1"></a>    <span class="at">upi =</span> <span class="fu">map_dbl</span>(<span class="st">`</span><span class="at">80%</span><span class="st">`</span>, <span class="sc">~</span>.<span class="sc">$</span>upper)</span>
<span id="cb25-7"><a href="exponential.html#cb25-7" tabindex="-1"></a>  )</span>
<span id="cb25-8"><a href="exponential.html#cb25-8" tabindex="-1"></a></span>
<span id="cb25-9"><a href="exponential.html#cb25-9" tabindex="-1"></a>palette_hw <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">`</span><span class="at">Additive Holt-Winters</span><span class="st">`</span> <span class="ot">=</span> <span class="st">&quot;goldenrod&quot;</span>, </span>
<span id="cb25-10"><a href="exponential.html#cb25-10" tabindex="-1"></a>                <span class="st">`</span><span class="at">Multiplicative Holt-Winters</span><span class="st">`</span> <span class="ot">=</span> <span class="st">&quot;seagreen&quot;</span>)</span>
<span id="cb25-11"><a href="exponential.html#cb25-11" tabindex="-1"></a></span>
<span id="cb25-12"><a href="exponential.html#cb25-12" tabindex="-1"></a>hw_fit <span class="sc">%&gt;%</span></span>
<span id="cb25-13"><a href="exponential.html#cb25-13" tabindex="-1"></a>  <span class="fu">augment</span>() <span class="sc">%&gt;%</span></span>
<span id="cb25-14"><a href="exponential.html#cb25-14" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> Quarter)) <span class="sc">+</span></span>
<span id="cb25-15"><a href="exponential.html#cb25-15" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> Trips)) <span class="sc">+</span></span>
<span id="cb25-16"><a href="exponential.html#cb25-16" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> .fitted, <span class="at">color =</span> .model)) <span class="sc">+</span></span>
<span id="cb25-17"><a href="exponential.html#cb25-17" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">data =</span> hw_fc, <span class="fu">aes</span>(<span class="at">y =</span> .mean, <span class="at">color =</span> .model)) <span class="sc">+</span></span>
<span id="cb25-18"><a href="exponential.html#cb25-18" tabindex="-1"></a>  <span class="fu">geom_ribbon</span>(<span class="at">data =</span> hw_fc, <span class="fu">aes</span>(<span class="at">ymin =</span> lpi, <span class="at">ymax =</span> upi, <span class="at">color =</span> .model, <span class="at">fill =</span> .model), </span>
<span id="cb25-19"><a href="exponential.html#cb25-19" tabindex="-1"></a>              <span class="at">alpha =</span> <span class="fl">0.2</span>) <span class="sc">+</span></span>
<span id="cb25-20"><a href="exponential.html#cb25-20" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> palette_hw) <span class="sc">+</span></span>
<span id="cb25-21"><a href="exponential.html#cb25-21" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> palette_hw) <span class="sc">+</span></span>
<span id="cb25-22"><a href="exponential.html#cb25-22" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">&quot;top&quot;</span>) <span class="sc">+</span></span>
<span id="cb25-23"><a href="exponential.html#cb25-23" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">color =</span> <span class="cn">NULL</span>, <span class="at">fill =</span> <span class="cn">NULL</span>, </span>
<span id="cb25-24"><a href="exponential.html#cb25-24" tabindex="-1"></a>       <span class="at">title =</span> <span class="st">&quot;Holt Winters Additive, ETS(A, A, A), and Multiplicative, ETS(M, A, M)&quot;</span>)</span></code></pre></div>
<p><img src="time-series_files/figure-html/unnamed-chunk-21-1.png" width="672" /></p>
</div>
</div>
<div id="model-selection-with-cv" class="section level2 hasAnchor" number="4.5">
<h2><span class="header-section-number">4.5</span> Model Selection with CV<a href="exponential.html#model-selection-with-cv" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Let’s compare the performance of a few candidate models for the base R datasets::WWWusage data set of internet usage.</p>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="exponential.html#cb26-1" tabindex="-1"></a>datasets<span class="sc">::</span>WWWusage <span class="sc">%&gt;%</span></span>
<span id="cb26-2"><a href="exponential.html#cb26-2" tabindex="-1"></a>  <span class="fu">as_tsibble</span>() <span class="sc">%&gt;%</span></span>
<span id="cb26-3"><a href="exponential.html#cb26-3" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> index, <span class="at">y =</span> value)) <span class="sc">+</span></span>
<span id="cb26-4"><a href="exponential.html#cb26-4" tabindex="-1"></a>  <span class="fu">geom_line</span>() <span class="sc">+</span></span>
<span id="cb26-5"><a href="exponential.html#cb26-5" tabindex="-1"></a>  <span class="fu">theme_light</span>() <span class="sc">+</span></span>
<span id="cb26-6"><a href="exponential.html#cb26-6" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Internet usage by minute&quot;</span>, <span class="at">x =</span> <span class="cn">NULL</span>, <span class="at">y =</span> <span class="st">&quot;Users&quot;</span>)</span></code></pre></div>
<p><img src="time-series_files/figure-html/unnamed-chunk-22-1.png" width="672" /></p>
<p>We will use time-series cross-validation. The data set has 100 rows. Function <code>stretch_tsibble(.init, .step)</code> takes a tsibble and creates a new tsibble for cross validation. First <code>stretch_tsibble()</code> takes the first <code>.init</code> rows from the tsibble and adds a new column <code>.id</code> with value 1. Then it takes the first <code>.init</code> + <code>.step</code> rows from the tsibble and assigns <code>.id</code> value 2. It continues like this, creating longer and longer tsibbles until it cannot create a longer one from the original tsibble. Finally, it appends these together into one long tsibble with <code>.id</code> added to the index. Nofmal cross-validation repeatedly fits a model to data set with one of the rows left out. Since <code>model()</code> fits a separate model per index value, creating this long tsibble effectively accomplishes the same thing. Note the fundamental difference here though: time seris CV does not leave out single values from points along in the time series. It leaves out <em>all</em> points after a particular point along the time series - each sub-data set starts at the beginning and is uninterrupted until reaching the varying end points. Let’s take a look at the CV data set before using it to fit the models.</p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="exponential.html#cb27-1" tabindex="-1"></a>www_cv <span class="ot">&lt;-</span> datasets<span class="sc">::</span>WWWusage <span class="sc">%&gt;%</span></span>
<span id="cb27-2"><a href="exponential.html#cb27-2" tabindex="-1"></a>  <span class="fu">as_tsibble</span>() <span class="sc">%&gt;%</span></span>
<span id="cb27-3"><a href="exponential.html#cb27-3" tabindex="-1"></a>  <span class="fu">stretch_tsibble</span>(<span class="at">.init =</span> <span class="dv">10</span>, <span class="at">.step =</span> <span class="dv">1</span>)</span>
<span id="cb27-4"><a href="exponential.html#cb27-4" tabindex="-1"></a></span>
<span id="cb27-5"><a href="exponential.html#cb27-5" tabindex="-1"></a><span class="co"># 10 rows + 11 rows + ... + 100 rows = 5,005 rows:</span></span>
<span id="cb27-6"><a href="exponential.html#cb27-6" tabindex="-1"></a><span class="fu">nrow</span>(www_cv)</span>
<span id="cb27-7"><a href="exponential.html#cb27-7" tabindex="-1"></a><span class="do">## [1] 5005</span></span>
<span id="cb27-8"><a href="exponential.html#cb27-8" tabindex="-1"></a></span>
<span id="cb27-9"><a href="exponential.html#cb27-9" tabindex="-1"></a><span class="co"># .id added to index</span></span>
<span id="cb27-10"><a href="exponential.html#cb27-10" tabindex="-1"></a><span class="fu">head</span>(www_cv)</span>
<span id="cb27-11"><a href="exponential.html#cb27-11" tabindex="-1"></a><span class="do">## # A tsibble: 6 x 3 [1]</span></span>
<span id="cb27-12"><a href="exponential.html#cb27-12" tabindex="-1"></a><span class="do">## # Key:       .id [1]</span></span>
<span id="cb27-13"><a href="exponential.html#cb27-13" tabindex="-1"></a><span class="do">##   index value   .id</span></span>
<span id="cb27-14"><a href="exponential.html#cb27-14" tabindex="-1"></a><span class="do">##   &lt;dbl&gt; &lt;dbl&gt; &lt;int&gt;</span></span>
<span id="cb27-15"><a href="exponential.html#cb27-15" tabindex="-1"></a><span class="do">## 1     1    88     1</span></span>
<span id="cb27-16"><a href="exponential.html#cb27-16" tabindex="-1"></a><span class="do">## 2     2    84     1</span></span>
<span id="cb27-17"><a href="exponential.html#cb27-17" tabindex="-1"></a><span class="do">## 3     3    85     1</span></span>
<span id="cb27-18"><a href="exponential.html#cb27-18" tabindex="-1"></a><span class="do">## 4     4    85     1</span></span>
<span id="cb27-19"><a href="exponential.html#cb27-19" tabindex="-1"></a><span class="do">## 5     5    84     1</span></span>
<span id="cb27-20"><a href="exponential.html#cb27-20" tabindex="-1"></a><span class="do">## 6     6    85     1</span></span>
<span id="cb27-21"><a href="exponential.html#cb27-21" tabindex="-1"></a></span>
<span id="cb27-22"><a href="exponential.html#cb27-22" tabindex="-1"></a><span class="co"># 91 index values</span></span>
<span id="cb27-23"><a href="exponential.html#cb27-23" tabindex="-1"></a><span class="fu">summary</span>(www_cv<span class="sc">$</span>.id)</span>
<span id="cb27-24"><a href="exponential.html#cb27-24" tabindex="-1"></a><span class="do">##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. </span></span>
<span id="cb27-25"><a href="exponential.html#cb27-25" tabindex="-1"></a><span class="do">##    1.00   42.00   62.00   58.55   78.00   91.00</span></span></code></pre></div>
<p>Fit four models to the 91 data sets to compare the accuracy. Here’s the full code.</p>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="exponential.html#cb28-1" tabindex="-1"></a>datasets<span class="sc">::</span>WWWusage <span class="sc">%&gt;%</span></span>
<span id="cb28-2"><a href="exponential.html#cb28-2" tabindex="-1"></a>  <span class="fu">as_tsibble</span>() <span class="sc">%&gt;%</span></span>
<span id="cb28-3"><a href="exponential.html#cb28-3" tabindex="-1"></a>  <span class="fu">stretch_tsibble</span>(<span class="at">.init =</span> <span class="dv">10</span>, <span class="at">.step =</span> <span class="dv">1</span>) <span class="sc">%&gt;%</span></span>
<span id="cb28-4"><a href="exponential.html#cb28-4" tabindex="-1"></a>  <span class="fu">model</span>(</span>
<span id="cb28-5"><a href="exponential.html#cb28-5" tabindex="-1"></a>    <span class="at">OLS =</span> <span class="fu">TSLM</span>(value <span class="sc">~</span> index),</span>
<span id="cb28-6"><a href="exponential.html#cb28-6" tabindex="-1"></a>    <span class="st">`</span><span class="at">Simple Exponential Smoothing</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">ETS</span>(value <span class="sc">~</span> <span class="fu">error</span>(<span class="st">&quot;A&quot;</span>) <span class="sc">+</span> <span class="fu">trend</span>(<span class="st">&quot;N&quot;</span>) <span class="sc">+</span> <span class="fu">season</span>(<span class="st">&quot;N&quot;</span>)),</span>
<span id="cb28-7"><a href="exponential.html#cb28-7" tabindex="-1"></a>    <span class="st">`</span><span class="at">Holt&#39;s method</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">ETS</span>(value <span class="sc">~</span> <span class="fu">error</span>(<span class="st">&quot;A&quot;</span>) <span class="sc">+</span> <span class="fu">trend</span>(<span class="st">&quot;A&quot;</span>) <span class="sc">+</span> <span class="fu">season</span>(<span class="st">&quot;N&quot;</span>)),</span>
<span id="cb28-8"><a href="exponential.html#cb28-8" tabindex="-1"></a>    <span class="st">`</span><span class="at">Holt&#39;s method (damped)</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">ETS</span>(value <span class="sc">~</span> <span class="fu">error</span>(<span class="st">&quot;A&quot;</span>) <span class="sc">+</span> <span class="fu">trend</span>(<span class="st">&quot;Ad&quot;</span>) <span class="sc">+</span> <span class="fu">season</span>(<span class="st">&quot;N&quot;</span>))</span>
<span id="cb28-9"><a href="exponential.html#cb28-9" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb28-10"><a href="exponential.html#cb28-10" tabindex="-1"></a>  <span class="fu">forecast</span>(<span class="at">h =</span> <span class="dv">1</span>) <span class="sc">%&gt;%</span></span>
<span id="cb28-11"><a href="exponential.html#cb28-11" tabindex="-1"></a>  <span class="fu">accuracy</span>(<span class="at">data =</span> <span class="fu">as_tsibble</span>(datasets<span class="sc">::</span>WWWusage))</span></code></pre></div>
<pre><code>## Warning: The future dataset is incomplete, incomplete out-of-sample data will be treated as missing. 
## 1 observation is missing at 101</code></pre>
<pre><code>## # A tibble: 4 × 10
##   .model               .type      ME  RMSE   MAE     MPE  MAPE  MASE RMSSE  ACF1
##   &lt;chr&gt;                &lt;chr&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
## 1 Holt&#39;s method        Test   0.0610  3.87  3.17   0.244  2.38 0.701 0.668 0.296
## 2 Holt&#39;s method (damp… Test   0.288   3.69  3.00   0.347  2.26 0.663 0.636 0.336
## 3 OLS                  Test  -6.01   38.7  31.4  -10.8   24.8  6.94  6.67  0.974
## 4 Simple Exponential … Test   1.46    6.05  4.81   0.904  3.55 1.06  1.04  0.803</code></pre>
<p>The best model as measured by RMSE was Holt’s method with damping. OLS was pretty bad. Let’s fit it to the whole data set and forecast future periods.</p>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="exponential.html#cb31-1" tabindex="-1"></a>www_fit <span class="ot">&lt;-</span> datasets<span class="sc">::</span>WWWusage <span class="sc">%&gt;%</span></span>
<span id="cb31-2"><a href="exponential.html#cb31-2" tabindex="-1"></a>  <span class="fu">as_tsibble</span>() <span class="sc">%&gt;%</span></span>
<span id="cb31-3"><a href="exponential.html#cb31-3" tabindex="-1"></a>  <span class="fu">model</span>(<span class="at">holt_d =</span> <span class="fu">ETS</span>(value <span class="sc">~</span> <span class="fu">error</span>(<span class="st">&quot;A&quot;</span>) <span class="sc">+</span> <span class="fu">trend</span>(<span class="st">&quot;Ad&quot;</span>) <span class="sc">+</span> <span class="fu">season</span>(<span class="st">&quot;N&quot;</span>)))</span>
<span id="cb31-4"><a href="exponential.html#cb31-4" tabindex="-1"></a></span>
<span id="cb31-5"><a href="exponential.html#cb31-5" tabindex="-1"></a>www_fit <span class="sc">%&gt;%</span> <span class="fu">report</span>()</span></code></pre></div>
<pre><code>## Series: value 
## Model: ETS(A,Ad,N) 
##   Smoothing parameters:
##     alpha = 0.9999 
##     beta  = 0.9966439 
##     phi   = 0.814958 
## 
##   Initial states:
##      l[0]        b[0]
##  90.35177 -0.01728234
## 
##   sigma^2:  12.2244
## 
##      AIC     AICc      BIC 
## 717.7310 718.6342 733.3620</code></pre>
<p>This time the damping parameter is very small (0.815), resulting in a quick return to the horizontal.</p>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="exponential.html#cb33-1" tabindex="-1"></a>www_fc <span class="ot">&lt;-</span> www_fit <span class="sc">%&gt;%</span></span>
<span id="cb33-2"><a href="exponential.html#cb33-2" tabindex="-1"></a>  <span class="fu">forecast</span>(<span class="at">h =</span> <span class="dv">10</span>) <span class="sc">%&gt;%</span></span>
<span id="cb33-3"><a href="exponential.html#cb33-3" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">sigma =</span> <span class="fu">map_dbl</span>(value, <span class="sc">~</span><span class="fu">unlist</span>(.) <span class="sc">%&gt;%</span> .[<span class="st">&quot;mu&quot;</span>]),</span>
<span id="cb33-4"><a href="exponential.html#cb33-4" tabindex="-1"></a>         <span class="at">ci_025 =</span> <span class="fu">qnorm</span>(.<span class="dv">025</span>, .mean, sigma),</span>
<span id="cb33-5"><a href="exponential.html#cb33-5" tabindex="-1"></a>         <span class="at">ci_975 =</span> <span class="fu">qnorm</span>(.<span class="dv">975</span>, .mean, sigma))</span>
<span id="cb33-6"><a href="exponential.html#cb33-6" tabindex="-1"></a></span>
<span id="cb33-7"><a href="exponential.html#cb33-7" tabindex="-1"></a>www_fit <span class="sc">%&gt;%</span></span>
<span id="cb33-8"><a href="exponential.html#cb33-8" tabindex="-1"></a>  <span class="fu">augment</span>() <span class="sc">%&gt;%</span></span>
<span id="cb33-9"><a href="exponential.html#cb33-9" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> index)) <span class="sc">+</span></span>
<span id="cb33-10"><a href="exponential.html#cb33-10" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> value)) <span class="sc">+</span></span>
<span id="cb33-11"><a href="exponential.html#cb33-11" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> .fitted), <span class="at">color =</span> <span class="st">&quot;goldenrod&quot;</span>) <span class="sc">+</span></span>
<span id="cb33-12"><a href="exponential.html#cb33-12" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">data =</span> www_fc, <span class="fu">aes</span>(<span class="at">y =</span> .mean), <span class="at">color =</span> <span class="st">&quot;goldenrod&quot;</span>) <span class="sc">+</span></span>
<span id="cb33-13"><a href="exponential.html#cb33-13" tabindex="-1"></a>  <span class="fu">geom_ribbon</span>(<span class="at">data =</span> www_fc, <span class="fu">aes</span>(<span class="at">ymin =</span> ci_025, <span class="at">ymax =</span> ci_975), <span class="at">alpha =</span> <span class="fl">0.2</span>, <span class="at">fill =</span> <span class="st">&quot;goldenrod&quot;</span>) <span class="sc">+</span></span>
<span id="cb33-14"><a href="exponential.html#cb33-14" tabindex="-1"></a>  <span class="fu">theme_light</span>() <span class="sc">+</span></span>
<span id="cb33-15"><a href="exponential.html#cb33-15" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Internet usage by Minute.&quot;</span>, </span>
<span id="cb33-16"><a href="exponential.html#cb33-16" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">&quot;Holt&#39;s method with damping. Shaded are is 95% prediction interval.&quot;</span>,</span>
<span id="cb33-17"><a href="exponential.html#cb33-17" tabindex="-1"></a>       <span class="at">x =</span> <span class="cn">NULL</span>)</span></code></pre></div>
<pre><code>## Warning: The output of `fortify(&lt;fable&gt;)` has changed to better suit usage with the ggdist package.
## If you&#39;re using it to extract intervals, consider using `hilo()` to compute intervals, and `unpack_hilo()` to obtain values.
## The output of `fortify(&lt;fable&gt;)` has changed to better suit usage with the ggdist package.
## If you&#39;re using it to extract intervals, consider using `hilo()` to compute intervals, and `unpack_hilo()` to obtain values.</code></pre>
<p><img src="time-series_files/figure-html/unnamed-chunk-26-1.png" width="672" /></p>
</div>
<div id="model-selection-via-maximum-likelihood" class="section level2 hasAnchor" number="4.6">
<h2><span class="header-section-number">4.6</span> Model Selection via Maximum Likelihood<a href="exponential.html#model-selection-via-maximum-likelihood" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>If you specify an ETS model with no parameters, it will use maximum likelihood to select the model with the minimum AIC<sub>c</sub>. Try it with the internet usage data set.</p>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="exponential.html#cb35-1" tabindex="-1"></a>ets_mdl <span class="ot">&lt;-</span> datasets<span class="sc">::</span>WWWusage <span class="sc">%&gt;%</span></span>
<span id="cb35-2"><a href="exponential.html#cb35-2" tabindex="-1"></a>  <span class="fu">as_tsibble</span>() <span class="sc">%&gt;%</span></span>
<span id="cb35-3"><a href="exponential.html#cb35-3" tabindex="-1"></a>  <span class="fu">model</span>(<span class="fu">ETS</span>(value))</span>
<span id="cb35-4"><a href="exponential.html#cb35-4" tabindex="-1"></a></span>
<span id="cb35-5"><a href="exponential.html#cb35-5" tabindex="-1"></a>ets_mdl <span class="sc">%&gt;%</span> <span class="fu">report</span>()</span></code></pre></div>
<pre><code>## Series: value 
## Model: ETS(A,Ad,N) 
##   Smoothing parameters:
##     alpha = 0.9999 
##     beta  = 0.9966439 
##     phi   = 0.814958 
## 
##   Initial states:
##      l[0]        b[0]
##  90.35177 -0.01728234
## 
##   sigma^2:  12.2244
## 
##      AIC     AICc      BIC 
## 717.7310 718.6342 733.3620</code></pre>
<p>ETS chose an additive damped trend model, the same as we found using cross validation.</p>

</div>
</div>
<div class="footnotes">
<hr />
<ol start="1">
<li id="fn1"><p>The trend can also be multiplicative (M) or multiplicative damped (M<sub>d</sub>), but <a href="https://otexts.com/fpp3/taxonomy.html">Hyndman</a> explains that they do not produce good forecasts.<a href="exponential.html#fnref1" class="footnote-back">↩︎</a></p></li>
<li id="fn2"><p>Innovation residuals are residuals on the transformed scale if the outcome variable was transformed.<a href="exponential.html#fnref2" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="regression.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="arima.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["time-series.pdf", "time-series.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
